### ISSUE TITLE
file Upload not working

### ISSUE THREAD

**Issue by MrunaliBhatt** [DNNCommunity/DNN.Forum#1]
I am using this module in my website, but none of the files with any of the extensions are uploading, it says server error, not able to change the rights, it says internal server error, while clicking on the menu-bar of the control panel, it is redirected to an error page.
plz help me

**Comment by juvander** [comment]
Anything in the den logs?

**Comment by MrunaliBhatt** [comment]
No it was a bug, it is solved with the new version
