### ISSUE TITLE
Some PostConnector (public API) improvements

### ISSUE THREAD

**Issue by roman-yagodin** [DNNCommunity/DNN.Forum#11]
Some nice things to have in public API:
- Ability to customize `IsPinned` then calling `SubmitExternalPost()` - currently always `False`, and `PostValidation()` method is private.
- Ability to get newly created post id somehow - e.g. to generate link to it. `PostToDatabase()` returns it, but it also private and heavily wrapped in `PostValidation()`.

**Comment by juvander** [comment]
Need to see, especially this new post id is buried quite deep.

**Comment by juvander** [comment]
Added another SubmitExternalPost with IsPinned as a new parameter

**Comment by roman-yagodin** [comment]
Wow, thanks for `IsPinned` - you are very kind! It will sure help with creating new forum post to discuss from external source!

About new post id: it could be resolved by returning some structure (or class) like that:
```C#
public struct SubmitPostResult
{
    public int PostId;
    public PostMessage PostMessage;
}
```
It can be extended in the future to have more fields to return. But surely it looks like major change in API.

Similar approach could be applied to pass parameters to `SubmitExternalPost()`:

```C#
public struct SubmitPostParams
{
    public int TabId;
    public int ModuleId;
    public int ForumId;
    public int UserId;
    ...
    public List<Term> Terms;
}

public SubmitPostResult SubmitExternalPost (SubmitPostParams postParams);
```

**Comment by juvander** [comment]
That was my idea as well, but yes, there is lots of places where this is checked. Need to review this carefully.

**Comment by juvander** [comment]
Did a quick refactoring, see with this https://github.com/juvander/DotNetNuke-Forum/releases/tag/05.01.00_DNN8

**Comment by roman-yagodin** [comment]
Thanks, I'll check it.

**Comment by roman-yagodin** [comment]
Seems to work as intended.

**Comment by juvander** [comment]
Excellent!
