### ISSUE TITLE
Finnish adblock list - issue

### ISSUE THREAD

**Issue by THEtomaso** [DNNCommunity/DNN.Forum#13]
Hi.

Sorry for posting this in the wrong place, but you're the one who's maintaining the 'Finnish adblock list', right?

There's an issue with this rule:
`/pixel.gif$domain=~www.damnlol.com`

It blocks images at various sites (at least when used with uBlock Origin).
Here's a couple of examples (the second one is NSFW):
```
https://www.adlibris.com/
https://xhamster.com/photos/
```

You should probably remove the tilde symbol (~)

**Comment by juvander** [comment]
Wrong place

**Comment by THEtomaso** [comment]
Could you point me to the right place?
The only locations I were able to find was your forum and Facebook page.
Since I don't speak Finnish, and don't have a Facebook account, I found myself out of options.

--

**EDIT:**
OK, I've managed to find your e-mail address now, so I'll use that for any future reports.
But of course, I assume that there's no need to mail you the one that I've already posted here.
Sorry for the mess.
