### ISSUE TITLE
DnnCommunity organization

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.Forum#14]
Hi @juvander I see you have been maintaining this module on your repository, we are trying to merge all the old core modules into the DnnCommunity organization to coordinated efforts on this. You would get write access and be the official maintainer if you want to and receive more visibility and help from a team on coordinating efforts. We also meet every 2 weeks to discuss the future of the old core modules (most of them have been revived and we would like for the Forum module to be part of that). Let me know if you want to discuss, join that group. Thanks.

**Comment by juvander** [comment]
Sure.
