### ISSUE TITLE
CSS not loading when creating new module

### ISSUE THREAD

**Issue by Jobj-325** [DNNCommunity/DNN.Forum#15]
Hello,

I am new to DNN and want to start developing modules, I have followed [this blog](https://www.dnnsoftware.com/community-blog/cid/155076/designing-and-styling-the-view-control) for setting up the module and so far I have succesfully created a site, a new module(by using the template) in Visual Studio and I can display plain text on the site by typing it in my view.ascx file. 

However, when I follow the guide and insert the html in the view.ascx and the css in the module.css file, the CSS won't load in the module. The HTML does show up and adding inline styling in the HTML file itself works fine, the styling from the module.css does not show however.

Do I need to "include" the module.css file somewhere in the html file for it to work? Any feedback or help would be appreciated!

Job

**Comment by juvander** [comment]
Not related to DNN.Forum module
