### ISSUE TITLE
Version numbering?

### ISSUE THREAD

**Issue by Suprawow** [DNNCommunity/DNN.Forum#31]
Latest release says it's 05.01.01_DNN8 but the zip file is named 05.01.00.zip.
Surely both cannot be right.

**Comment by juvander** [comment]
Just a minor update to fix upgrade issue. Old version still left behind

**Comment by Suprawow** [comment]
Thanks.
So there's two different 05.01.00.zip???
I can't install that then, Github tells me the latest version is 05.01.01.zip but no file exists.
We have strict rules regarding versioning not this type of approach. Why so confusing?
