### ISSUE TITLE
Error thrown when posting, possibly generated by sending email notifications

### ISSUE THREAD

**Issue by sgraziosi** [DNNCommunity/DNN.Forum#4]
Hi,
thanks for writing this! After upgrading to DNN 8 (from 7.x to 8.0.3, specifically), the forum wasn't working, with [error](http://www.dnnsoftware.com/forums/threadid/527058/scope/posts/upgraded-to-8-forum-not-working):
InnerMessage:Could not load type 'DotNetNuke.Web.UI.WebControls.DnnComboBox' ...
as suggested, I installed this version of the forum (05.00.06_DNN8), and the problem was solved.
However, posting a new message now sends to an error page. The posting actually works, but no email notifications are sent. In the event log I find:

> ModuleId:5469
> ModuleDefId:127
> FriendlyName:
> ModuleControlSource:DesktopModules/Forum/Forum_PostEdit.ascx
> AbsoluteURL:/X/Default.aspx
> DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
> ExceptionGUID:9af92a41-2f3c-4fd7-8f02-eae9243e3267
> AssemblyVersion:8.0.3
> PortalId:35
> UserId:131
> TabId:2932
> RawUrl:/X/Default.aspx?tabid=2932&ctl=PostEdit&forumid=23&postid=1711&action=reply&mid=5469
> Referrer:https:/X/X/Default.aspx?tabid=2932&ctl=PostEdit&forumid=23&postid=1711&action=reply&mid=5469
> UserAgent:Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)
> ExceptionHash:l2JQe9CRwQ/0GKMcji1KeA==
> Message:Object reference not set to an instance of an object.
> StackTrace:
> InnerMessage:Object reference not set to an instance of an object.
> InnerStackTrace:
>    at DotNetNuke.Modules.Forum.Utilities.ForumUtils.AddHost(String URL, String PrimaryHost)
>    at DotNetNuke.Modules.Forum.Utilities.ForumUtils.FormatEmailImage(String mText, String PrimaryAlias)
>    at DotNetNuke.Modules.Forum.ForumEmail.FormatHTMLBody(Object Body, Configuration objConfig)
>    at DotNetNuke.Modules.Forum.ForumEmail.GenerateBody(String Notes, ForumContentTypeID ContentType, Hashtable Keywords, String BodyToParse, Configuration objConfig, Boolean HTML)
>    at DotNetNuke.Modules.Forum.ForumEmail.GenerateEmail(String Notes, ForumEmailType emailType, Int32 ContentID, Configuration objConfig, String URL, String ProfileURL, Int32 PortalID)
>    at DotNetNuke.Modules.Forum.Utilities.ForumUtils.SendForumMail(Int32 ContentID, String URL, ForumEmailType EmailType, String Notes, Configuration objConfig, String ProfileURL, Int32 PortalID)
>    at DotNetNuke.Modules.Forum.PostConnector.HandleNotifications(Boolean IsModerated, Configuration objConfig, PostInfo newPostInfo, ForumEmailType emailType, Int32 TabID, Int32 PortalID)
>    at DotNetNuke.Modules.Forum.PostConnector.PostToDatabase(Int32 TabID, Int32 ModuleID, Configuration objConfig, Int32 PortalID, ForumUserInfo objForumUser, String PostSubject, String PostBody, ForumInfo objForum, Int32 ParentPostID, Int32 PostID, Boolean IsPinned, Boolean IsClosed, Boolean ReplyNotify, ThreadStatus Status, String lstAttachmentFileIDs, String RemoteAddress, Int32 PollID, Int32 ThreadID, PostAction objAction, Boolean IsModerated, List`1 Terms)
>    at DotNetNuke.Modules.Forum.PostConnector.PostingValidation(Int32 TabID, Int32 ModuleID, Int32 PortalID, Int32 UserID, String PostSubject, String PostBody, Int32 ForumID, Int32 ParentPostID, Int32 PostID, Boolean IsPinned, Boolean IsClosed, Boolean ReplyNotify, ThreadStatus Status, String lstAttachmentFileIDs, String RemoteAddress, Int32 PollID, Boolean IsQuote, String Provider, Int32 ThreadID, List`1 Terms)
>    at DotNetNuke.Modules.Forum.PostConnector.SubmitInternalPost(Int32 TabID, Int32 ModuleID, Int32 PortalID, Int32 UserID, String PostSubject, String PostBody, Int32 ForumID, Int32 ParentPostID, Int32 PostID, Boolean IsPinned, Boolean IsClosed, Boolean ReplyNotify, ThreadStatus Status, String AttachmentFileIDs, String RemoteAddress, Int32 PollID, Boolean IsQuote, Int32 ThreadID, List`1 Terms)
>    at DotNetNuke.Modules.Forum.PostEdit.cmdSubmit_Click(Object sender, EventArgs e)
> Source:
> FileName:
> FileLineNumber:0
> FileColumnNumber:0
> Method:
> Server Name:

I realise this might be very difficult to reproduce: it is happening on our very old (and our only) DNN install, gone through lots of troublesome upgrades and moved across three "migrated" installs from one server to another (now running on an Azure VM). So it's far from your usual vanilla DNN instance!
In any case, I thought it would be good for you to know.
thanks and best wishes,
Sergio

**Comment by juvander** [comment]
Point to check: In site advanced settings->Site aliases, check that you have primary site alias selected.

**Comment by sgraziosi** [comment]
well spotted! couldn't find where to set this in the UI, but doing it on the PortalAlias table directly did the trick.
Out of interest, what is the primary site alias for? This particular portal has only one...
Thanks!

**Comment by juvander** [comment]
Have not checked, but this might be something that is changed along the DNN versions and now this is set by default to first one. If you have more than one alias, then you can choose what is the primary one. This alias is used when sending notification e-mails as link to post, most likely similar usage elsewhere in DNN as well.

This alias is found in section where you define those aliases in UI, advanced settings.

**Comment by sgraziosi** [comment]
thanks.
Take home message: go and check that portals with just one alias have it set to "primary". I've found how to do this in the UI, via "host\Site Management\edit[a given site]", I was previously looking in the "admin" section...
Much appreciated.
Sergio
