### ISSUE TITLE
Forum Avatars

### ISSUE THREAD

**Issue by Sunspoticus** [DNNCommunity/DNN.Forum#5]
DNN v8.0.3
DNN Forum, 5.0.6

Forum avatars are not displaying and the upload control in the forum profile section doesn't seem to be working..

In Forum/Admin/Users, what looks like an edit control doesn't seem to function either. dead click.

**Comment by juvander** [comment]
Are you using a custom css? Is your site public to take a peek?

**Comment by Sunspoticus** [comment]
Clarification: Its Super User's avatars which do not show...

Yes, our forums are public: http://extraordinarygamers.net. Anyone who has posted who's avatars aren't showing up are Supers.

**Comment by juvander** [comment]
Hmm - for example on this page I can see some but not all http://extraordinarygamers.net/Forums/forumid/13/threadid/31/scope/posts, sunspoticus is a super user?

**Comment by juvander** [comment]
Note that there used to be separate forum avatars, those were removed in https://github.com/juvander/DotNetNuke-Forum/releases/tag/05.00.05 so only avatars that are in use are the ones assigned in DNN user profile

**Comment by Sunspoticus** [comment]
Aye, "Sunspoticus" is me. Confirmed its just Supers, even if they have an avatar set..

**Comment by juvander** [comment]
Ok, found the place where this is coming. Need to verify why this line is there, must have a reason for it, just cannot understand why...

**Comment by Sunspoticus** [comment]
I hate it when that happens to me too..

**Comment by juvander** [comment]
See with this https://github.com/juvander/DotNetNuke-Forum/releases/tag/05.00.07_DNN8
Just removed those lines where it was checking this superuser stuff. Should not have really a reason not to show avatar for those.

**Comment by Sunspoticus** [comment]
Right on, thanks!
