### ISSUE TITLE
Problem with attachments

### ISSUE THREAD

**Issue by trouble2** [DNNCommunity/DNN.Forum#8]
Just tried to set up a forum module on dnn 8.0.3
When I try to add an attachment DNN errors:

he INSERT statement conflicted with the FOREIGN KEY constraint "FK_Forum_Attachment_Forum_Posts". The conflict occurred in database "dnn803", table "dbo.Forum_Posts", column 'PostID'. The statement has been terminated.

**Comment by juvander** [comment]
So it seems, will check this later on today.

**Comment by trouble2** [comment]
Cool, thanks for you quick reply….
So, your not travelling through Mongolia at the moment so it seems….
I’ve talked to you a while back in Spain and France, at the DNN conference.
Very funny to see you are managing the forum module now.
You’re doing a great job!!!

Marnix Bouwman
[cid:image006.png@01D0344A.F84A7D80]bond for web solutions

Van: Ilpo Juvander [mailto:notifications@github.com]
Verzonden: Wednesday, March 1, 2017 5:22 PM
Aan: juvander/DotNetNuke-Forum <DotNetNuke-Forum@noreply.github.com>
CC: Marnix Bouwman <marnixbouwman@bondforwebsolutions.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [juvander/DotNetNuke-Forum] Problem with attachments (#8)


So it seems, will check this later on today.

**Comment by juvander** [comment]
Aa - I see you when looking closer 😀 No, I'm already back and next longer trip is to DNNConnect again.

Looks like this bug has been there from version 4.5... need to see how this could be fixed...

**Comment by juvander** [comment]
Ok, here's the fix: execute this in your database:

ALTER TABLE [dbo].[Forum_Attachments] NOCHECK CONSTRAINT [FK_Forum_Attachment_Forum_Posts]

So this just adds WITH NOCHECK to the key, there is no other simple way to fix this before next release :(

**Comment by trouble2** [comment]
Wow, I wish everyone was that quick in fixing problems!!!
Thanks a lot Ilpo.
Perhaps I’ll see you again in Spain ☺

Marnix Bouwman
[cid:image006.png@01D0344A.F84A7D80]bond for web solutions

Van: Ilpo Juvander [mailto:notifications@github.com]
Verzonden: Wednesday, March 1, 2017 7:45 PM
Aan: juvander/DotNetNuke-Forum <DotNetNuke-Forum@noreply.github.com>
CC: Marnix Bouwman <marnixbouwman@bondforwebsolutions.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [juvander/DotNetNuke-Forum] Problem with attachments (#8)


Ok, here's the fix: execute this in your database:

ALTER TABLE [dbo].[Forum_Attachments] NOCHECK CONSTRAINT [FK_Forum_Attachment_Forum_Posts]

So this just adds WITH NOCHECK to the key, there is no other simple way to fix this before next release :(

**Comment by trouble2** [comment]
Hi Ilpo,
Do you know if the DNN forum has an integration with the DNN Journal module.
Because in the Journal module you can select to display “Forum posts” etc.
However, I don’t think it is working….

Regards,

Van: Ilpo Juvander [mailto:notifications@github.com]
Verzonden: Wednesday, March 1, 2017 5:22 PM
Aan: juvander/DotNetNuke-Forum <DotNetNuke-Forum@noreply.github.com>
CC: Marnix Bouwman <marnixbouwman@bondforwebsolutions.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [juvander/DotNetNuke-Forum] Problem with attachments (#8)


So it seems, will check this later on today.

**Comment by juvander** [comment]
Nothing on that in the source code. Forum module was already forgotten when that feature came out so no development has been around that.

**Comment by trouble2** [comment]
OK, thanks!

Marnix Bouwman
[cid:image006.png@01D0344A.F84A7D80]bond for web solutions

Van: Ilpo Juvander [mailto:notifications@github.com]
Verzonden: Wednesday, March 15, 2017 9:40 AM
Aan: juvander/DotNetNuke-Forum <DotNetNuke-Forum@noreply.github.com>
CC: Marnix Bouwman <marnixbouwman@bondforwebsolutions.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [juvander/DotNetNuke-Forum] Problem with attachments (#8)


Nothing on that in the source code. Forum module was already forgotten when that feature came out so no development has been around that.

**Comment by juvander** [comment]
See with this: https://github.com/juvander/DotNetNuke-Forum/releases/tag/05.01.00_DNN8

**Comment by trouble2** [comment]
Wow, you’ve been busy…
Is it ok for production, or do you expect a lot of bugs?

Marnix Bouwman
[cid:image006.png@01D0344A.F84A7D80]bond for web solutions

Van: Ilpo Juvander [mailto:notifications@github.com]
Verzonden: Thursday, March 16, 2017 11:45 AM
Aan: juvander/DotNetNuke-Forum <DotNetNuke-Forum@noreply.github.com>
CC: Marnix Bouwman <marnixbouwman@bondforwebsolutions.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [juvander/DotNetNuke-Forum] Problem with attachments (#8)


See with this: https://github.com/juvander/DotNetNuke-Forum/releases/tag/05.01.00_DNN8

**Comment by juvander** [comment]
I have this version now running on my own + few other sites. Not much other changes compared to previous one - yet. But of course, see how the journal now works before putting it into production. Especially the visibility of those entries ;)
